import { Sidebar } from "../_components/sidebar";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="hidden h-screen md:hidden lg:flex">
          <section className="w-[20%]">
            <Sidebar />
          </section>
          <section className="w-[80%] ">{children}</section>
        </main>
      </body>
    </html>
  );
}
